### ISSUE TITLE
Branch for 1.2.5 version

### ISSUE THREAD

**Issue by andeon** [morevnaproject/papagayo#12]
A lot of changes are coming on code, maybe is time to create a branch to 1.2.5 legacy.

**Comment by morevnaproject** [comment]
I have created release (tag) for 1.2-5 now.

**Comment by steveway** [comment]
Do I need to tag mine too or something? Just getting warm with git. @morevnaproject

**Comment by morevnaproject** [comment]
I think it's no need to do that. It's ok just to have it in the main repo for reference. ^__^
