### ISSUE TITLE
UI: Move all buttons related to export to separate row

### ISSUE THREAD

**Issue by morevnaproject** [morevnaproject/papagayo#3]
Currently all export buttons are in the same row as the breakdown buttons. That makes UI too wide (so buttons are squeezed). It would be logically to move them to separate row.

**Comment by morevnaproject** [comment]
@steveway, @MaskedRetriever, what do you think?

**Comment by steveway** [comment]
Sure, I'm not hanging onto the current layout.
I'm bad at layouting so I was lucky to be able to get that button to work in that place.

**Comment by MaskedRetriever** [comment]
Likewise!
