### ISSUE TITLE
"Image to Export" button should be insensitive when export format is not set to "Images"

### ISSUE THREAD

**Issue by morevnaproject** [morevnaproject/papagayo#4]

**Comment by steveway** [comment]
Yes, I was just looking to see if there is some code already where we can plug 
self.voiceimageBut.Disable()
and 
self.voiceimageBut.Enable()
into depending on the state of the current exportChoice, haven't found a good place yet.
I also haven't tested if those two lines are enough to disable and enable the button or if we need to do more.

**Comment by steveway** [comment]
I haven't tested this yet, need to do this later after work, but this might work to enable and disable it:
87b3acfe4e394dbcba4b2c9c7c06880d1845bbd8

**Comment by morevnaproject** [comment]
Works perfectly with a little fix. Thank you! ^__^
