### ISSUE TITLE
Position marker doesn't update on newer wxPython versions

### ISSUE THREAD

**Issue by steveway** [morevnaproject/papagayo#7]
So, I thought this was a problem wit my port to wxPython_Phoenix, but this also happens on python 2 with regular wxPython 3.0.2.0.
On Playback, as soon as the current reaches the end of the current screen and the view scrolls the cursor stays at the left.
I would appreciate if someone can verify if this isn't a local problem for me or if this is a general problem.
I have a hacky fix for this in my python 3 port.
You might wan't to take a look into this file between line 432 and 450:
https://github.com/steveway/papagayo-1/blob/py3phoenix/WaveformView.py
I would really like it if someone came up with a better solution, especially one he understands.

**Comment by morevnaproject** [comment]
I cannot reproduce this problem with current status of master branch (python2, commit fa3cc7ffa8). Ubuntu 15.10, python-wxgtk2.8 version 2.8.12.1+dfsg2-2ubuntu2.

**Comment by steveway** [comment]
Yes, as far as I know it works with 2.8, but this seems to break on 3.0.
I would guess that this is not a bug in wxpython but more likely with papagayo, especially since I was able to kinda fix the same problem on wxphoenix. Would be nice if someone could test this with wxpython 3 just to make sure that it's not me.

**Comment by steveway** [comment]
Seems to work in the current version. So I'll close this for now.
